import{a as $,S as I,i as s}from"./assets/vendor-DSElq03b.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function a(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=a(r);fetch(r.href,o)}})();const x="51387635-d1faa43170eec50f2b7d86b54",B="https://pixabay.com/api/";async function M(t,e=1){const a={key:x,q:encodeURIComponent(t),image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};try{return(await $.get(B,{params:a})).data}catch(i){throw new Error(`Failed to fetch images: ${i.message}`)}}const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),b=document.querySelector(".load-more");let h=null;function L(t){const e=t.map(({webformatURL:a,largeImageURL:i,tags:r,likes:o,views:c,comments:E,downloads:R})=>`
        <li class="photo-card">
          <a href="${i}">
            <img src="${a}" alt="${r}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${o}</p>
            <p><b>Views:</b> ${c}</p>
            <p><b>Comments:</b> ${E}</p>
            <p><b>Downloads:</b> ${R}</p>
          </div>
        </li>
      `).join("");m.insertAdjacentHTML("beforeend",e),p()}function w(){m.innerHTML=""}function f(){y.classList.add("is-visible")}function g(){y.classList.remove("is-visible")}function v(){b.classList.remove("is-hidden")}function l(){b.classList.add("is-hidden")}function p(){console.log("Lightbox updated"),h?h.refresh():h=new I(".gallery a",{captionsData:"alt",captionDelay:250})}let d=1,S=1,u="",n=0;document.querySelector(".form").addEventListener("submit",async t=>{t.preventDefault();const e=t.target.elements["search-text"],a=e.value.trim();if(!a){s.error({title:"Error",message:"Please enter a search term!",position:"topRight"});return}a!==u&&(O(a),u=a),w(),l(),f();try{const i=await P(a);i.hits.length===0?s.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(L(i.hits),p(),i.hits.length<15||n<=d*15?(l(),n>0&&s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v(),q())}catch{s.error({title:"Error",message:"There was an error loading the images. Please try again.",position:"topRight"})}finally{g(),e.value=""}});document.querySelector(".load-more").addEventListener("click",async()=>{d+=1,f(),l();try{const t=await P(u);L(t.hits),p(),d*15>=n||t.hits.length<15?(l(),s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v(),q()}catch{s.error({title:"Error",message:"There was an error loading the images. Please try again.",position:"topRight"})}finally{g()}});async function P(t){f();try{const e=await M(t,d);return n=e.totalHits,S=Math.ceil(n/15),e}catch(e){throw new Error(`Failed to fetch images: ${e.message}`)}finally{g()}}function q(){var e;const t=((e=document.querySelector(".photo-card"))==null?void 0:e.getBoundingClientRect().height)||0;window.scrollBy({top:t*2,behavior:"smooth"})}function O(t){d=1,S=1,u=t,n=0,w(),l()}
//# sourceMappingURL=index.js.map
