import{a as R,i as n,S as $}from"./assets/vendor-DSElq03b.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const I="51387635-d1faa43170eec50f2b7d86b54",M="https://pixabay.com/api/";async function x(e,t=1){const s={key:I,q:encodeURIComponent(e),image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};try{return(await R.get(M,{params:s})).data}catch(i){throw new Error(`Failed to fetch images: ${i.message}`)}}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more");function b(e){if(!e||e.length===0){f.innerHTML='<li style="grid-column: 1 / -1; text-align: center; font-size: 18px; color: #666;">No images found.</li>';return}const t=e.map(({webformatURL:s,largeImageURL:i,tags:r,likes:o,views:c,comments:q,downloads:E})=>`
        <li class="photo-card">
          <a href="${i}">
            <img src="${s}" alt="${r}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${o}</p>
            <p><b>Views:</b> ${c}</p>
            <p><b>Comments:</b> ${q}</p>
            <p><b>Downloads:</b> ${E}</p>
          </div>
        </li>
      `).join("");f.insertAdjacentHTML("beforeend",t)}function L(){f.innerHTML=""}function g(){m.classList.add("is-visible")}function p(){m.classList.remove("is-visible")}function w(){y.classList.remove("is-hidden")}function d(){y.classList.add("is-hidden")}let u=1,v=1,h="",l=0,a;document.querySelector(".form").addEventListener("submit",async e=>{e.preventDefault();const t=e.target.elements["search-text"],s=t.value.trim();if(!s){n.error({title:"Error",message:"Please enter a search term!",position:"topRight"});return}s!==h&&(B(s),h=s),L(),d(),g();try{const i=await S(s);i.hits.length===0?n.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(b(i.hits),a||(a=new $(".gallery a",{captionsData:"alt",captionDelay:250})),a.refresh(),i.hits.length<15||l<=u*15?(d(),l>0&&n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w(),P())}catch{n.error({title:"Error",message:"There was an error loading the images. Please try again.",position:"topRight"})}finally{p(),t.value=""}});document.querySelector(".load-more").addEventListener("click",async()=>{u+=1,g(),d();try{const e=await S(h);b(e.hits),a.refresh(),u*15>=l||e.hits.length<15?(d(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w(),P()}catch{n.error({title:"Error",message:"There was an error loading the images. Please try again.",position:"topRight"})}finally{p()}});async function S(e){g();try{const t=await x(e,u);return l=t.totalHits,v=Math.ceil(l/15),t}catch(t){throw new Error(`Failed to fetch images: ${t.message}`)}finally{p()}}function P(){var t;const e=((t=document.querySelector(".photo-card"))==null?void 0:t.getBoundingClientRect().height)||0;window.scrollBy({top:e*2,behavior:"smooth"})}function B(e){u=1,v=1,h=e,l=0,L(),a&&(a.destroy(),a=null),d()}
//# sourceMappingURL=index.js.map
