import{a as R,S as B,i as n}from"./assets/vendor-DDdXnYQq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const $="51387635-d1faa43170eec50f2b7d86b54",I="https://pixabay.com/api/",l=15;async function m(o,t=1){const i={key:$,q:encodeURIComponent(o),image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:l};try{return(await R.get(I,{params:i})).data}catch(s){throw new Error(`Failed to fetch images: ${s.message}`)}}const g=document.querySelector(".gallery"),y=document.querySelector(".loader"),b=document.querySelector(".load-more");let f;function L(o){const t=o.map(({webformatURL:i,largeImageURL:s,tags:e,likes:r,views:c,comments:E,downloads:q})=>`
        <li class="photo-card">
          <a href="${s}">
            <img src="${i}" alt="${e}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${r}</p>
            <p><b>Views:</b> ${c}</p>
            <p><b>Comments:</b> ${E}</p>
            <p><b>Downloads:</b> ${q}</p>
          </div>
        </li>
      `).join("");g.insertAdjacentHTML("beforeend",t),f?f.refresh():f=new B(".gallery a",{captionsData:"alt",captionDelay:250})}function M(){g.innerHTML=""}function w(){y.classList.add("is-visible")}function p(){y.classList.remove("is-visible")}function v(){b.classList.remove("is-hidden")}function u(){b.classList.add("is-hidden")}let a=1,d="",h=0;const P=document.querySelector(".form"),O=document.querySelector(".load-more"),x=P.elements["search-text"];P.addEventListener("submit",async o=>{o.preventDefault();const t=x.value.trim();if(!t){n.error({title:"Error",message:"Please enter a search term!",position:"topRight"});return}t!==d&&(d=t,A()),w();try{const i=await m(d,a);if(h=i.totalHits,i.hits.length===0){n.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),p();return}L(i.hits),a*l>=h||i.hits.length<l?(u(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v(),S()}catch{n.error({title:"Error",message:"There was an error loading the images. Please try again.",position:"topRight"})}finally{p()}});O.addEventListener("click",async()=>{a+=1,w(),u();try{const o=await m(d,a);L(o.hits),a*l>=h||o.hits.length<l?(u(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v(),S()}catch{n.error({title:"Error",message:"There was an error loading the images. Please try again.",position:"topRight"})}finally{p()}});function S(){var t;const o=((t=document.querySelector(".photo-card"))==null?void 0:t.getBoundingClientRect().height)||0;window.scrollBy({top:o*2,behavior:"smooth"})}function A(){a=1,h=0,M(),u()}
//# sourceMappingURL=index.js.map
